#!/bin/bash
#### App file generated with YoloGen, the YunoHost app generator, version .

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

ynh_backup "/etc/watchdog.conf"

# Remove other various files specific to the app... such as :

ynh_backup "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
